package net.models;

// Generated 27 mars 2014 20:49:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Participate generated by hbm2java
 */
@Entity
@Table(name = "participate", catalog = "scrumtool")
public class Participate implements java.io.Serializable {

	private ParticipateId id;
	private Sprint sprint;
	private Role role;
	private Collaborator collaborator;

	public Participate() {
	}

	public Participate(ParticipateId id, Sprint sprint, Role role,
			Collaborator collaborator) {
		this.id = id;
		this.sprint = sprint;
		this.role = role;
		this.collaborator = collaborator;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idSprint", column = @Column(name = "idSprint", nullable = false)),
			@AttributeOverride(name = "idCollaborator", column = @Column(name = "idCollaborator", nullable = false)),
			@AttributeOverride(name = "idRole", column = @Column(name = "idRole", nullable = false)) })
	public ParticipateId getId() {
		return this.id;
	}

	public void setId(ParticipateId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSprint", nullable = false, insertable = false, updatable = false)
	public Sprint getSprint() {
		return this.sprint;
	}

	public void setSprint(Sprint sprint) {
		this.sprint = sprint;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRole", nullable = false, insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCollaborator", nullable = false, insertable = false, updatable = false)
	public Collaborator getCollaborator() {
		return this.collaborator;
	}

	public void setCollaborator(Collaborator collaborator) {
		this.collaborator = collaborator;
	}

}
