package net.models;

// Generated 27 mars 2014 20:49:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlayroleId generated by hbm2java
 */
@Embeddable
public class PlayroleId implements java.io.Serializable {

	private int idCollaborator;
	private int idRole;
	private int idProduct;

	public PlayroleId() {
	}

	public PlayroleId(int idCollaborator, int idRole, int idProduct) {
		this.idCollaborator = idCollaborator;
		this.idRole = idRole;
		this.idProduct = idProduct;
	}

	@Column(name = "idCollaborator", nullable = false)
	public int getIdCollaborator() {
		return this.idCollaborator;
	}

	public void setIdCollaborator(int idCollaborator) {
		this.idCollaborator = idCollaborator;
	}

	@Column(name = "idRole", nullable = false)
	public int getIdRole() {
		return this.idRole;
	}

	public void setIdRole(int idRole) {
		this.idRole = idRole;
	}

	@Column(name = "idProduct", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlayroleId))
			return false;
		PlayroleId castOther = (PlayroleId) other;

		return (this.getIdCollaborator() == castOther.getIdCollaborator())
				&& (this.getIdRole() == castOther.getIdRole())
				&& (this.getIdProduct() == castOther.getIdProduct());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCollaborator();
		result = 37 * result + this.getIdRole();
		result = 37 * result + this.getIdProduct();
		return result;
	}

}