package net.models;

// Generated 27 mars 2014 20:49:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Playrole generated by hbm2java
 */
@Entity
@Table(name = "playrole", catalog = "scrumtool")
public class Playrole implements java.io.Serializable {

	private PlayroleId id;
	private Role role;
	private Product product;
	private Collaborator collaborator;

	public Playrole() {
	}

	public Playrole(PlayroleId id, Role role, Product product,
			Collaborator collaborator) {
		this.id = id;
		this.role = role;
		this.product = product;
		this.collaborator = collaborator;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idCollaborator", column = @Column(name = "idCollaborator", nullable = false)),
			@AttributeOverride(name = "idRole", column = @Column(name = "idRole", nullable = false)),
			@AttributeOverride(name = "idProduct", column = @Column(name = "idProduct", nullable = false)) })
	public PlayroleId getId() {
		return this.id;
	}

	public void setId(PlayroleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRole", nullable = false, insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProduct", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCollaborator", nullable = false, insertable = false, updatable = false)
	public Collaborator getCollaborator() {
		return this.collaborator;
	}

	public void setCollaborator(Collaborator collaborator) {
		this.collaborator = collaborator;
	}

}